# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nfs/zfs-student-3/users/2013_paris/ycribier/.brew/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /nfs/zfs-student-3/users/2013_paris/ycribier/.brew/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/zfs-student-3/users/2013_paris/ycribier/Work/cpp/nibbler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/zfs-student-3/users/2013_paris/ycribier/Work/cpp/nibbler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Volumes/Data/nfs/zfs-student-3/users/2013_paris/ycribier/.brew/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Volumes/Data/nfs/zfs-student-3/users/2013_paris/ycribier/.brew/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-3/users/2013_paris/ycribier/Work/cpp/nibbler/CMakeFiles /nfs/zfs-student-3/users/2013_paris/ycribier/Work/cpp/nibbler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-3/users/2013_paris/ycribier/Work/cpp/nibbler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nibbler

# Build rule for target.
nibbler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nibbler
.PHONY : nibbler

# fast build rule for target.
nibbler/fast:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/build
.PHONY : nibbler/fast

src/DynamicLibHandler.class.o: src/DynamicLibHandler.class.cpp.o
.PHONY : src/DynamicLibHandler.class.o

# target to build an object file
src/DynamicLibHandler.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/DynamicLibHandler.class.cpp.o
.PHONY : src/DynamicLibHandler.class.cpp.o

src/DynamicLibHandler.class.i: src/DynamicLibHandler.class.cpp.i
.PHONY : src/DynamicLibHandler.class.i

# target to preprocess a source file
src/DynamicLibHandler.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/DynamicLibHandler.class.cpp.i
.PHONY : src/DynamicLibHandler.class.cpp.i

src/DynamicLibHandler.class.s: src/DynamicLibHandler.class.cpp.s
.PHONY : src/DynamicLibHandler.class.s

# target to generate assembly for a file
src/DynamicLibHandler.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/DynamicLibHandler.class.cpp.s
.PHONY : src/DynamicLibHandler.class.cpp.s

src/Game.class.o: src/Game.class.cpp.o
.PHONY : src/Game.class.o

# target to build an object file
src/Game.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Game.class.cpp.o
.PHONY : src/Game.class.cpp.o

src/Game.class.i: src/Game.class.cpp.i
.PHONY : src/Game.class.i

# target to preprocess a source file
src/Game.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Game.class.cpp.i
.PHONY : src/Game.class.cpp.i

src/Game.class.s: src/Game.class.cpp.s
.PHONY : src/Game.class.s

# target to generate assembly for a file
src/Game.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Game.class.cpp.s
.PHONY : src/Game.class.cpp.s

src/GameEntity.class.o: src/GameEntity.class.cpp.o
.PHONY : src/GameEntity.class.o

# target to build an object file
src/GameEntity.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/GameEntity.class.cpp.o
.PHONY : src/GameEntity.class.cpp.o

src/GameEntity.class.i: src/GameEntity.class.cpp.i
.PHONY : src/GameEntity.class.i

# target to preprocess a source file
src/GameEntity.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/GameEntity.class.cpp.i
.PHONY : src/GameEntity.class.cpp.i

src/GameEntity.class.s: src/GameEntity.class.cpp.s
.PHONY : src/GameEntity.class.s

# target to generate assembly for a file
src/GameEntity.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/GameEntity.class.cpp.s
.PHONY : src/GameEntity.class.cpp.s

src/Lib.o: src/Lib.cpp.o
.PHONY : src/Lib.o

# target to build an object file
src/Lib.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Lib.cpp.o
.PHONY : src/Lib.cpp.o

src/Lib.i: src/Lib.cpp.i
.PHONY : src/Lib.i

# target to preprocess a source file
src/Lib.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Lib.cpp.i
.PHONY : src/Lib.cpp.i

src/Lib.s: src/Lib.cpp.s
.PHONY : src/Lib.s

# target to generate assembly for a file
src/Lib.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Lib.cpp.s
.PHONY : src/Lib.cpp.s

src/Map.class.o: src/Map.class.cpp.o
.PHONY : src/Map.class.o

# target to build an object file
src/Map.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Map.class.cpp.o
.PHONY : src/Map.class.cpp.o

src/Map.class.i: src/Map.class.cpp.i
.PHONY : src/Map.class.i

# target to preprocess a source file
src/Map.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Map.class.cpp.i
.PHONY : src/Map.class.cpp.i

src/Map.class.s: src/Map.class.cpp.s
.PHONY : src/Map.class.s

# target to generate assembly for a file
src/Map.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Map.class.cpp.s
.PHONY : src/Map.class.cpp.s

src/Player.class.o: src/Player.class.cpp.o
.PHONY : src/Player.class.o

# target to build an object file
src/Player.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Player.class.cpp.o
.PHONY : src/Player.class.cpp.o

src/Player.class.i: src/Player.class.cpp.i
.PHONY : src/Player.class.i

# target to preprocess a source file
src/Player.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Player.class.cpp.i
.PHONY : src/Player.class.cpp.i

src/Player.class.s: src/Player.class.cpp.s
.PHONY : src/Player.class.s

# target to generate assembly for a file
src/Player.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Player.class.cpp.s
.PHONY : src/Player.class.cpp.s

src/Snake.class.o: src/Snake.class.cpp.o
.PHONY : src/Snake.class.o

# target to build an object file
src/Snake.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Snake.class.cpp.o
.PHONY : src/Snake.class.cpp.o

src/Snake.class.i: src/Snake.class.cpp.i
.PHONY : src/Snake.class.i

# target to preprocess a source file
src/Snake.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Snake.class.cpp.i
.PHONY : src/Snake.class.cpp.i

src/Snake.class.s: src/Snake.class.cpp.s
.PHONY : src/Snake.class.s

# target to generate assembly for a file
src/Snake.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Snake.class.cpp.s
.PHONY : src/Snake.class.cpp.s

src/Time.class.o: src/Time.class.cpp.o
.PHONY : src/Time.class.o

# target to build an object file
src/Time.class.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Time.class.cpp.o
.PHONY : src/Time.class.cpp.o

src/Time.class.i: src/Time.class.cpp.i
.PHONY : src/Time.class.i

# target to preprocess a source file
src/Time.class.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Time.class.cpp.i
.PHONY : src/Time.class.cpp.i

src/Time.class.s: src/Time.class.cpp.s
.PHONY : src/Time.class.s

# target to generate assembly for a file
src/Time.class.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/Time.class.cpp.s
.PHONY : src/Time.class.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nibbler"
	@echo "... src/DynamicLibHandler.class.o"
	@echo "... src/DynamicLibHandler.class.i"
	@echo "... src/DynamicLibHandler.class.s"
	@echo "... src/Game.class.o"
	@echo "... src/Game.class.i"
	@echo "... src/Game.class.s"
	@echo "... src/GameEntity.class.o"
	@echo "... src/GameEntity.class.i"
	@echo "... src/GameEntity.class.s"
	@echo "... src/Lib.o"
	@echo "... src/Lib.i"
	@echo "... src/Lib.s"
	@echo "... src/Map.class.o"
	@echo "... src/Map.class.i"
	@echo "... src/Map.class.s"
	@echo "... src/Player.class.o"
	@echo "... src/Player.class.i"
	@echo "... src/Player.class.s"
	@echo "... src/Snake.class.o"
	@echo "... src/Snake.class.i"
	@echo "... src/Snake.class.s"
	@echo "... src/Time.class.o"
	@echo "... src/Time.class.i"
	@echo "... src/Time.class.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

